// Compiles bin/main.dart to a CommonJS module for Node.js.
//
//   dart run tool/build.dart <output.js>
//
// The bundle is the node_preamble (browser globals dart2js expects), the
// dart2js output, then `module.exports = self.dhametEngine`.
import 'dart:io';

import 'package:node_preamble/preamble.dart' as preamble;

Future<void> main(List<String> args) async {
  if (args.length != 1) {
    stderr.writeln('usage: dart run tool/build.dart <output.js>');
    exit(64);
  }
  final output = File(args.single);
  final temp = await Directory.systemTemp.createTemp('dhamet_engine_bridge');
  try {
    final compiled = '${temp.path}/main.js';
    final result = await Process.run(Platform.resolvedExecutable, [
      'compile',
      'js',
      '-O2',
      '--no-source-maps',
      '-o',
      compiled,
      'bin/main.dart',
    ]);
    stdout.write(result.stdout);
    stderr.write(result.stderr);
    if (result.exitCode != 0) exit(result.exitCode);
    await output.parent.create(recursive: true);
    await output.writeAsString(
      [
        '// GENERATED by server/engine_bridge/tool/build.dart. Do not edit.',
        preamble.getPreamble(minified: true),
        await File(compiled).readAsString(),
        'module.exports = self.dhametEngine;',
        '',
      ].join('\n'),
    );
    stdout.writeln('Wrote ${output.path}');
  } finally {
    await temp.delete(recursive: true);
  }
}
